default nn
label nn
   kernel /boot/Image
   fdtdir /boot/
   fdtoverlays /boot/ti/k3-am67a-beagley-ai-csi0-imx708.dtbo /boot/ti/k3-am67a-beagley-ai-vision-apps.dtbo
   append root=PARTUUID=6e6e6279-02 rootwait rw console=ttyS2,115200n8 panic=10 init=/sbin/init watchdog.open_timeout=120
